[package]
name = "winvirtualdesktops"
version = "0.0.1"
authors = ["Jari Otto Oskari Pennanen <ciantic@oksidi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "wtypesbase", "hstring", "guiddef"] }
com = "0.2.0"


[lib]
name = "winvirtualdesktops"
path = "src/lib.rs"

[features]
debug = []


[workspace]
members = [
    "testbin",
]