[package]
name = "winvirtualdesktopstestbin"
version = "0.0.1"
authors = ["Jari Otto Oskari Pennanen <ciantic@oksidi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "wtypesbase", "hstring", "guiddef"] }
winvirtualdesktops = { path = "../", features = ["debug"] }

[[bin]]
name = "testwinvirtualdesktops"
path = "src/main.rs"
